export const countries = [
    { value: 'Afghanistan', label: 'افغانستان (Afghanistan)' },
    { value: 'Albania', label: 'Shqipëria (Albania)' },
    { value: 'Algeria', label: 'الجزائر (Algeria)' },
    { value: 'Andorra', label: 'Andorra' },
    { value: 'Angola', label: 'Angola' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Armenia', label: 'Հայաստան (Armenia)' },
    { value: 'Australia', label: 'Australia' },
    { value: 'Austria', label: 'Österreich (Austria)' },
    { value: 'Azerbaijan', label: 'Azərbaycan (Azerbaijan)' },
    { value: 'Bahamas', label: 'Bahamas' },
    { value: 'Bahrain', label: 'البحرين (Bahrain)' },
    { value: 'Bangladesh', label: 'বাংলাদেশ (Bangladesh)' },
    { value: 'Barbados', label: 'Barbados' },
    { value: 'Belarus', label: 'Беларусь (Belarus)' },
    { value: 'Belgium', label: 'België / Belgique (Belgium)' },
    { value: 'Belize', label: 'Belize' },
    { value: 'Benin', label: 'Bénin' },
    { value: 'Bhutan', label: 'འབྲུག་ཡུལ་ (Bhutan)' },
    { value: 'Bolivia', label: 'Bolivia' },
    { value: 'Bosnia and Herzegovina', label: 'Bosna i Hercegovina' },
    { value: 'Botswana', label: 'Botswana' },
    { value: 'Brazil', label: 'Brasil (Brazil)' },
    { value: 'Brunei', label: 'Brunei' },
    { value: 'Bulgaria', label: 'България (Bulgaria)' },
    { value: 'Burkina Faso', label: 'Burkina Faso' },
    { value: 'Burundi', label: 'Burundi' },
    { value: 'Cambodia', label: 'កម្ពុជា (Cambodia)' },
    { value: 'Cameroon', label: 'Cameroun (Cameroon)' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Cape Verde', label: 'Cabo Verde' },
    { value: 'Central African Republic', label: 'République centrafricaine' },
    { value: 'Chad', label: 'Tchad / تشاد' },
    { value: 'Chile', label: 'Chile' },
    { value: 'China', label: '中国 (China)' },
    { value: 'Colombia', label: 'Colombia' },
    { value: 'Comoros', label: 'Comores / جزر القمر' },
    { value: 'Congo (Congo-Brazzaville)', label: 'Congo' },
    { value: 'Congo (Democratic Republic)', label: 'Rép. dém. du Congo' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Croatia', label: 'Hrvatska (Croatia)' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'Cyprus', label: 'Κύπρος / Kıbrís' },
    { value: 'Czech Republic', label: 'Česko (Czech Republic)' },
    { value: 'Denmark', label: 'Danmark (Denmark)' },
    { value: 'Djibouti', label: 'Djibouti / جيبوتي' },
    { value: 'Dominica', label: 'Dominica' },
    { value: 'Dominican Republic', label: 'República Dominicana' },
    { value: 'Ecuador', label: 'Ecuador' },
    { value: 'Egypt', label: 'مصر (Egypt)' },
    { value: 'El Salvador', label: 'El Salvador' },
    { value: 'Equatorial Guinea', label: 'Guinea Ecuatorial' },
    { value: 'Eritrea', label: 'Ertrer / إري트리아' },
    { value: 'Estonia', label: 'Eesti (Estonia)' },
    { value: 'Eswatini', label: 'eSwatini' },
    { value: 'Ethiopia', label: 'ኢትዮጵያ (Ethiopia)' },
    { value: 'Fiji', label: 'Fiji' },
    { value: 'Finland', label: 'Suomi / Finland' },
    { value: 'France', label: 'France' },
    { value: 'Gabon', label: 'Gabon' },
    { value: 'Gambia', label: 'Gambia' },
    { value: 'Georgia', label: 'საქართველო (Georgia)' },
    { value: 'Germany', label: 'Deutschland (Germany)' },
    { value: 'Ghana', label: 'Ghana' },
    { value: 'Greece', label: 'Ελλάδα (Greece)' },
    { value: 'Grenada', label: 'Grenada' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Guinea', label: 'Guinée' },
    { value: 'Guinea-Bissau', label: 'Guiné-Bissau' },
    { value: 'Guyana', label: 'Guyana' },
    { value: 'Haiti', label: 'Haïti' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Hungary', label: 'Magyarország (Hungary)' },
    { value: 'Iceland', label: 'Ísland (Iceland)' },
    { value: 'India', label: 'India / भारत' },
    { value: 'Indonesia', label: 'Indonesia' },
    { value: 'Iran', label: 'ایران (Iran)' },
    { value: 'Iraq', label: 'العراق (Iraq)' },
    { value: 'Ireland', label: 'Éire / Ireland' },
    { value: 'Israel', label: 'ישראל (Israel)' },
    { value: 'Italy', label: 'Italia (Italy)' },
    { value: 'Ivory Coast', label: 'Côte d’Ivoire' },
    { value: 'Jamaica', label: 'Jamaica' },
    { value: 'Japan', label: '日本 (Japan)' },
    { value: 'Jordan', label: 'الأردن (Jordan)' },
    { value: 'Kazakhstan', label: 'Қазақстан / Казахстан' },
    { value: 'Kenya', label: 'Kenya' },
    { value: 'Kiribati', label: 'Kiribati' },
    { value: 'Kuwait', label: 'الكويت (Kuwait)' },
    { value: 'Kyrgyzstan', label: 'Кыргызстан / Киргизия' },
    { value: 'Laos', label: 'ລາວ (Laos)' },
    { value: 'Latvia', label: 'Latvija (Latvia)' },
    { value: 'Lebanon', label: 'لبنان (Lebanon)' },
    { value: 'Lesotho', label: 'Lesotho' },
    { value: 'Liberia', label: 'Liberia' },
    { value: 'Libya', label: 'ليبيا (Libya)' },
    { value: 'Liechtenstein', label: 'Liechtenstein' },
    { value: 'Lithuania', label: 'Lietuva (Lithuania)' },
    { value: 'Luxembourg', label: 'Luxembourg / Lëtzebuerg / Luxemburg' },
    { value: 'Madagascar', label: 'Madagasikara' },
    { value: 'Malawi', label: 'Malawi' },
    { value: 'Malaysia', label: 'Malaysia' },
    { value: 'Maldives', label: 'ދިވެހިރާއްޖེ་ (Maldives)' },
    { value: 'Mali', label: 'Mali' },
    { value: 'Malta', label: 'Malta' },
    { value: 'Marshall Islands', label: 'Marshall Islands' },
    { value: 'Mauritania', label: 'موريتانيا (Mauritania)' },
    { value: 'Mauritius', label: 'Mauritius' },
    { value: 'Mexico', label: 'México (Mexico)' },
    { value: 'Micronesia', label: 'Micronesia' },
    { value: 'Moldova', label: 'Moldova' },
    { value: 'Monaco', label: 'Monaco' },
    { value: 'Mongolia', label: 'Монгол улс (Mongolia)' },
    { value: 'Montenegro', label: 'Crna Gora (Montenegro)' },
    { value: 'Morocco', label: 'المغرب (Morocco)' },
    { value: 'Mozambique', label: 'Moçambique' },
    { value: 'Myanmar', label: 'မြန်မာ (Myanmar)' },
    { value: 'Namibia', label: 'Namibia' },
    { value: 'Nauru', label: 'Naoero / Nauru' },
    { value: 'Nepal', label: 'नेपाल (Nepal)' },
    { value: 'Netherlands', label: 'Nederland (Netherlands)' },
    { value: 'New Zealand', label: 'New Zealand / Aotearoa' },
    { value: 'Nicaragua', label: 'Nicaragua' },
    { value: 'Niger', label: 'Niger' },
    { value: 'Nigeria', label: 'Nigeria' },
    { value: 'North Korea', label: '조선 (North Korea)' },
    { value: 'North Macedonia', label: 'Северна Македонија' },
    { value: 'Norway', label: 'Norge / Noreg' },
    { value: 'Oman', label: 'عمان (Oman)' },
    { value: 'Pakistan', label: 'پاکستان (Pakistan)' },
    { value: 'Palau', label: 'Palau / Belau' },
    { value: 'Palestine', label: 'فلسطين (Palestine)' },
    { value: 'Panama', label: 'Panamá' },
    { value: 'Papua New Guinea', label: 'Papua New Guinea' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Peru', label: 'Perú' },
    { value: 'Philippines', label: 'Pilipinas / Philippines' },
    { value: 'Poland', label: 'Polska (Poland)' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Qatar', label: 'قطر (Qatar)' },
    { value: 'Romania', label: 'România (Romania)' },
    { value: 'Russia', label: 'Россия (Russia)' },
    { value: 'Rwanda', label: 'Rwanda' },
    { value: 'Saint Kitts and Nevis', label: 'St. Kitts and Nevis' },
    { value: 'Saint Lucia', label: 'St. Lucia' },
    { value: 'Saint Vincent and the Grenadines', label: 'St. Vincent & Grenadines' },
    { value: 'Samoa', label: 'Samoa' },
    { value: 'San Marino', label: 'San Marino' },
    { value: 'Sao Tome and Principe', label: 'São Tomé e Príncipe' },
    { value: 'Saudi Arabia', label: 'المملكة العربية السعودية' },
    { value: 'Senegal', label: 'Sénégal' },
    { value: 'Serbia', label: 'Srbija (Serbia)' },
    { value: 'Seychelles', label: 'Seychelles / Sesel' },
    { value: 'Sierra Leone', label: 'Sierra Leone' },
    { value: 'Singapore', label: 'Singapore' },
    { value: 'Slovakia', label: 'Slovensko (Slovakia)' },
    { value: 'Slovenia', label: 'Slovenija (Slovenia)' },
    { value: 'Solomon Islands', label: 'Solomon Islands' },
    { value: 'Somalia', label: 'Soomaaliya / الصومال' },
    { value: 'South Africa', label: 'South Africa' },
    { value: 'South Korea', label: '대한민국 (South Korea)' },
    { value: 'South Sudan', label: 'South Sudan' },
    { value: 'Spain', label: 'España (Spain)' },
    { value: 'Sri Lanka', label: 'Sri Lanka / இலங்கை' },
    { value: 'Sudan', label: 'السودان (Sudan)' },
    { value: 'Suriname', label: 'Suriname' },
    { value: 'Sweden', label: 'Sverige (Sweden)' },
    { value: 'Switzerland', label: 'Schweiz / Suisse / Svizzera / Svizra' },
    { value: 'Syria', label: 'سوريا (Syria)' },
    { value: 'Taiwan', label: '台灣 (Taiwan)' },
    { value: 'Tajikistan', label: 'Тоҷикистон (Tajikistan)' },
    { value: 'Tanzania', label: 'Tanzania' },
    { value: 'Thailand', label: 'ประเทศไทย (Thailand)' },
    { value: 'Timor-Leste', label: 'Timor-Leste' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Tonga', label: 'Tonga' },
    { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
    { value: 'Tunisia', label: 'تونس (Tunisia)' },
    { value: 'Turkey', label: 'Türkiye (Turkey)' },
    { value: 'Turkmenistan', label: 'Türkmenistan' },
    { value: 'Tuvalu', label: 'Tuvalu' },
    { value: 'Uganda', label: 'Uganda' },
    { value: 'Ukraine', label: 'Україна (Ukraine)' },
    { value: 'United Arab Emirates', label: 'الإمارات العربية المتحدة' },
    { value: 'United Kingdom', label: 'United Kingdom' },
    { value: 'United States', label: 'United States' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Uzbekistan', label: 'Oʻzbekiston (Uzbekistan)' },
    { value: 'Vanuatu', label: 'Vanuatu' },
    { value: 'Vatican City', label: 'Città del Vaticano' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Vietnam', label: 'Việt Nam (Vietnam)' },
    { value: 'Yemen', label: 'اليمن (Yemen)' },
    { value: 'Zambia', label: 'Zambia' },
    { value: 'Zimbabwe', label: 'Zimbabwe' }
];
